global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
- channel: '#ivan_guba'