# указываем дистрибутив, который берем за основу
FROM ubuntu:16.04 

# обновляем кэш репозитория и ставим необходимые пакеты
RUN apt-get update
RUN apt-get install -y mongodb-server ruby-full ruby-dev build-essential git
RUN gem install bundler

# выкачиваем приложение в контейнер
RUN git clone -b monolith https://github.com/express42/reddit.git

# копируем файлы конфигурации в контейнер
COPY mongod.conf /etc/mongod.conf
COPY db_config /reddit/db_config
COPY start.sh /start.sh

# устанавливаем зависимости и производим настройку
RUN cd /reddit && bundle install
RUN chmod 0777 /start.sh

# старт сервиса
CMD ["/start.sh"]

# запускаем СБОРКУ ОБРАЗА командой 'docker build -t reddit:latest .' Точка в конце обязательна, путь до docker-контекста Флаг '-t' задает тэг для собранного образа
# смотрим все оборазы командой 'docker images -a'
# запускаем контейнер командой 'docker run --name reddit -d --network=host reddit:latest'