---
version: '3.3'
services:
  post_db:
    image: mongo:${MongoVer}
    volumes:
      - post_db:/data/db
    networks:
      BackNet: 
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${Username}/ui:latest
    ports:
      - ${HostPort}:${ContainerPort}/tcp
    networks:
      - FrontNet
  post:
    image: ${Username}/post:latest
    networks:
      FrontNet:
        aliases:
          - post
      BackNet:
        aliases:
          - post
  comment:
    image: ${Username}/comment:latest
    networks:
      FrontNet:
        aliases:
          - comment
      BackNet:
        aliases:
          - comment

volumes:
  post_db:

networks:
  FrontNet:
    ipam:
      config:
        - subnet: ${FNSubnet}
  BackNet:
    ipam:
      config:
        - subnet: ${BNSubnet}

  

  
