---
version: '3.3'
services:
  prometheus:
    image: ${Username}/prometheus:latest
    ports:
      - '9090:9090/tcp'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - FrontNet
      - BackNet
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - FrontNet
      - BackNet 
  cadvisor:
    image: google/cadvisor:v0.29.0
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - 8080:8080/tcp
    networks:
      BackNet:
        aliases:
          - cadvisor
      FrontNet:
        aliases:
          - cadvisor
  grafana:
    image: grafana/grafana:5.0.0
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    ports:
      - 3000:3000/tcp
    networks:
      BackNet:
        aliases:
          - grafana
      FrontNet:
        aliases:
          - grafana
  alertmanager:
    image: ${Username}/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - 9093:9093/tcp
    networks:
      BackNet:
        aliases:
          - alertmanager
      FrontNet:
        aliases:
          - alertmanager

volumes:
  prometheus_data:
  grafana_data:

networks:
  FrontNet:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  BackNet:
    ipam:
      config:
        - subnet: 10.0.2.0/24

