kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: 4+jntXFR0PfeZkT+GpoDF+ajhrwCSraK8PtV4ur+UYE=
      - identity: {}
